default:
  image: rust:alpine3.20
  before_script:
    - apk add --no-cache alpine-sdk
    - rustc --version
    - cargo --version
  tags:
    - shared-fi

variables:
  PROJECT_NAME: "bip380"

stages:
  - build_test_lint

build_test_lint:
  stage: build_test_lint
  script:
    - echo "Building ${PROJECT_NAME} project..."
    - cargo build --verbose
    - echo "Testing ${PROJECT_NAME} project..."
    - cargo test
    - echo "Checking formatting via rustfmt for ${PROJECT_NAME}..."
    - rustup component add rustfmt
    - cargo fmt -- --check
    - echo "Checking for clippy warnings for ${PROJECT_NAME}..."
    - rustup component add clippy
    - cargo clippy -- -D warnings
